### ISSUE TITLE
highlight and code blocks

### ISSUE THREAD

**Issue by visualcurrent** [GuangluWu/obsidian-pisum#1]
This is a really nice theme! And it's a great idea to use the light/dark to switch between normal/Matushak. 

Highlighting seems to have visibility issues in Edit mode on code blocks of text. Not only is the selected highlight appear too similar to the code block color, but changing the color shows that the highlighting is obscured behind the code block entity. 

Obsidian v0.7.3

**Comment by GuangluWu** [comment]
@goodsignal  Thank you for that. I believe I have corrected it. Have a try and let me know if you have any further request.
